export { default as ReactLogo } from "./react.png";
export { default as AngularLogo } from "./angular.png";
export { default as LaravelLogo } from "./laravel.png";
export { default as TailwindLogo } from "./tailwind.png";
export { default as WebLogo } from "./web-logo.png";
export { default as GithubLogo } from "./github.png";
export { default as MyPicture } from "./my-picture.png";
export { default as BoAPI } from "./bo-api.jpg";
export { default as Mtci } from "./mtci-logo.jpg";
export { default as Nsrc } from "./nsrc.png";
export { default as ApplyCorporate } from "./applycorporate-logo.png";
export { default as PostmanLogo } from "./postman-logo.png";
export { default as DockerLogo } from "./docker-logo.png";
export { default as LinuxLogo } from "./linux-logo.png";
export { default as PortalAdmin } from "./portal-admin.png";
export { default as NewBorn } from "./newborn-logo.png"
export { default as AboutPicV3 } from "./about-picV3.jpg";
export { default as MySql } from "./mysql.png";
export { default as FastApi } from "./fastapi.png";
export { default as Azure } from "./azure-image.png";
export { default as Finxp } from "./finxp-logo.jpg";
export { default as Unexus } from "./unexus-logo.png";
export { default as Taskus } from "./taskus-logo.png";
export { default as Dynata } from "./dynata-logo.jpg";
export {default as CompanyAward } from "./company-award.jpg";
export { default as CompanyAwardV2 } from "./company-awardv2.jpg";
export { default as FinxpAward } from "./finxp-award.png";
export { default as MongoLogo } from "./mongo-logo.png";
export { default as PhpLogo } from "./php-logo.png";
export { default as NestJS } from "./nestJS.png";
export { default as NextJS } from "./nextJS.png";
export { default as TypeScript } from "./typescript.png";
export { default as Yondu } from "./yondu_logo.jpeg"
export { default as GTS } from "./gts_logo.jpeg"

