export { default as ReactLogo } from "./react.png";
export { default as AngularLogo } from "./angular.png";
export { default as LaravelLogo } from "./laravel.png";
export { default as TailwindLogo } from "./tailwind.png";
export { default as WebLogo } from "./web-logo.png";
export { default as GithubLogo } from "./github.png";
export { default as MyPicture } from "./my-picture.png";
export { default as BoAPI } from "./bo-api.jpg";
export { default as Mtci } from "./mtci.jpg";
export { default as Nsrc } from "./nsrc.png";
export { default as ApplyCorporate } from "./apply-corporate.png";
export { default as PostmanLogo } from "./postman-logo.png";
export { default as DockerLogo } from "./docker-logo.png";
export { default as LinuxLogo } from "./linux-logo.png";
export { default as PortalAdmin } from "./portal-admin.png";
export { default as NewBorn } from "./new-born.jpg"
export { default as AboutPicV3 } from "./about-picV3.jpg"
